version: '3.2'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 202100 #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - /data/mysql/data/db:/var/lib/mysql #数据文件挂载
      - /data/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /data/mysql/log:/var/log/mysql #日志文件挂载
